kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  schemaAddress: next.registry.io:5001/myorg/application/schema:latest
  linkedCollections: 
    - next.registry.io:5001/myorg/myapp@sha256:6fe2350ee37d388f702519d4b3d3114aa92809a2fb42bbfa1120f34ca8dc1ac3
  files:
    - file: "heyworld"
      attributes:
        name: mydependentapp
        majorVersion: 1
        minorVersion: 0
        patchVersion: 0
