kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  linkedCollections: 
    - next.registry.io:5001/myorg/myapp@sha256:35fb5a8e0787b879a37974194fd493245047b133ec02849494cff79027f00faf

  schemaAddress: next.registry.io:5001/myorg/cves/schema:latest
  files:
    - file: "*.json"
      attributes:
        cveId: "CVE-1337-1234"
        assignerOrgId: "b3476cb9-2e3d-41a6-98d0-0f47421a65b6"
        url: "https://example.org/ESA-22-11-CVE-1337-1234"
